repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.7.9'
    hooks:
      - id: flake8
        args: [--max-line-length=120]
        additional_dependencies: [
          'flake8-bugbear==19.8.0'
        ]
  
  - repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3.9
        args: [--line-length=120]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910'
    hooks:
      - id: mypy
        args: [--strict]

  - repo: https://github.com/pycqa/isort
    rev: "5.9.3"
    hooks:
      - id: isort

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system
        entry: pytest
        pass_filenames: false
        always_run: true
        stages: [commit]
