[db]
mongo_image = "mongo:5.0.1"
mongo_express_image = "mongo-express:0.54.0"
mongo_db = "nedrex"
# root_directory = ""
volume_root = "nedrex"

[db.dev]
mongo_port = 27018
mongo_express_port = 8082
network = "nedrex_dev"
container_name = "nedrex_dev"
express_container_name = "nedrex_dev_express"

[db.live]
mongo_port = 27017
mongo_express_port = 8081
network = "nedrex_live"
container_name = "nedrex_live"
express_container_name = "nedrex_live_express"

[sources]
# directory = ""

[sources.biogrid]
[sources.biogrid.human_data]
filename = "homo_sapiens.tab3"

[sources.clinvar]
[sources.clinvar.human_data]
url = "https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/clinvar.vcf.gz"

[sources.disgenet]
[sources.disgenet.gene_disease_associations]
url = "https://www.disgenet.org/static/disgenet_ap1/files/downloads/curated_gene_disease_associations.tsv.gz"


# [sources.drugbank]
# username = ""
# password = ""

[sources.drugbank.all]
url = "https://go.drugbank.com/releases/5-1-8/downloads/all-full-database"
filename = "drugbank.zip"


[sources.drug_central]
[sources.drug_central.postgres_dump]
url = "http://unmtid-shinyapps.net/download/drugcentral-pgdump_20200918.sql.gz"
filename = "drug_central.sql.gz"


[sources.hpo]
[sources.hpo.obo]
url = "http://purl.obolibrary.org/obo/hp.obo"

[sources.hpo.annotations]
url = "http://purl.obolibrary.org/obo/hp/hpoa/phenotype.hpoa"


[sources.intact]
[sources.intact.psimitab]
url = "http://ftp.ebi.ac.uk/pub/databases/intact/current/psimitab/intact.zip"


[sources.mondo]
[sources.mondo.json]
url = "http://purl.obolibrary.org/obo/mondo.json"


[sources.ncbi]
[sources.ncbi.gene_info]
url = "https://ftp.ncbi.nih.gov/gene/DATA/GENE_INFO/Mammalia/Homo_sapiens.gene_info.gz"


# [sources.omim]
# [sources.omim.genemap2]
# url = ""


[sources.reactome]
[sources.reactome.uniprot_annotations]
url = "https://reactome.org/download/current/UniProt2Reactome_PE_All_Levels.txt"


[sources.uniprot]
[sources.uniprot.swissprot]
url = "https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/taxonomic_divisions/uniprot_sprot_human.dat.gz"

[sources.uniprot.trembl]
url = "https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/taxonomic_divisions/uniprot_trembl_human.dat.gz"

[sources.uniprot.idmapping]
url = "https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/idmapping/by_organism/HUMAN_9606_idmapping_selected.tab.gz"
